import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

// Minimal terms of service. Needs to exist for PayPal / SePay compliance.
// Keep language plain; this is not a substitute for counsel but covers the
// baseline: acceptance, plan tiers, refunds, prohibited use, liability,
// governing law, and contact.
export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-gray-900">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-8">
          <ArrowLeft className="w-4 h-4" /> Back to home
        </Link>
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: April 2026</p>

        <div className="prose prose-gray max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-2">1. Agreement</h2>
            <p className="text-gray-700">
              By creating an account on testmaster.pro ("IELTS Ace"), you agree to these Terms. If you don't agree, don't
              create an account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">2. Plans and billing</h2>
            <ul className="list-disc pl-5 space-y-1 text-gray-700">
              <li><strong>Free plan</strong> — limited monthly usage for evaluator, Liz, and practice. No card required.</li>
              <li><strong>Weekly / Monthly plans</strong> — recurring access. Cancel anytime; cancellation takes effect at the end of the current paid period.</li>
              <li><strong>Exam pass</strong> — one-time purchase for a fixed window of full-test practice and evaluations.</li>
              <li>Prices are shown at checkout. Taxes, where applicable, are added on top.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">3. Refunds</h2>
            <p className="text-gray-700">
              We offer a <strong>7-day refund</strong> from the date of purchase if you have not used more than 20% of the
              plan's included evaluations or test attempts. Email <a href="mailto:support@testmaster.pro" className="text-violet-600 hover:underline">support@testmaster.pro</a> with
              your account email and transaction ID.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">4. Acceptable use</h2>
            <p className="text-gray-700">You agree <strong>not</strong> to:</p>
            <ul className="list-disc pl-5 space-y-1 text-gray-700 mt-2">
              <li>Submit content that is illegal, harassing, or infringes copyright.</li>
              <li>Attempt to reverse-engineer, scrape, or overload the service.</li>
              <li>Share your account credentials. One account = one person.</li>
              <li>Use IELTS Ace to cheat on a real IELTS exam. We help you prepare, not impersonate.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">5. Content you submit</h2>
            <p className="text-gray-700">
              You keep ownership of the essays, answers, and messages you submit. You grant us a limited license to
              process that content solely to provide the service (evaluation, tutoring, your progress dashboard).
              See our <Link to="/privacy" className="text-violet-600 hover:underline">Privacy Policy</Link> for detail.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">6. AI output disclaimer</h2>
            <p className="text-gray-700">
              Band scores, feedback, and Liz chat responses are generated by AI with teacher-tuned prompts. They are
              guidance, not an official IELTS assessment. For official results, book an IELTS exam with the British
              Council, IDP, or Cambridge.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">7. Limitation of liability</h2>
            <p className="text-gray-700">
              The service is provided "as is." To the extent permitted by law, our total liability for any claim is
              limited to the amount you paid us in the 12 months before the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">8. Changes</h2>
            <p className="text-gray-700">
              We may update these Terms. Material changes will be announced via email or in-app notice at least 14 days
              before taking effect.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">9. Contact</h2>
            <p className="text-gray-700">
              Questions? <a href="mailto:support@testmaster.pro" className="text-violet-600 hover:underline">support@testmaster.pro</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
